# Generated by Django 5.1.4 on 2024-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profit', models.FloatField()),
                ('profit_change', models.FloatField()),
                ('rank', models.IntegerField()),
                ('rank_change', models.IntegerField(null=True)),
                ('revenue', models.FloatField()),
                ('revenue_change', models.FloatField()),
                ('years_in_rank', models.IntegerField()),
                ('assets', models.FloatField()),
                ('employees', models.IntegerField()),
            ],
            options={
                'db_table': 'default_companies',
            },
        ),
    ]
