# Generated by Django 5.1.4 on 2024-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcda_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('field', models.CharField(max_length=255, unique=True)),
                ('default_weight', models.FloatField()),
            ],
            options={
                'db_table': 'default_criteria',
            },
        ),
    ]
