# Generated by Django 5.1.4 on 2024-12-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcda_api', '0002_defaultcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcriteria',
            name='type',
            field=models.CharField(default='max', max_length=50),
        ),
    ]
