# Generated by Django 5.1.4 on 2024-12-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcda_api', '0003_defaultcriteria_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_weights', models.JSONField()),
                ('ranked_companies', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ahp_method',
            },
        ),
        migrations.CreateModel(
            name='CachedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('criteria_weights', models.TextField()),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cached_results',
            },
        ),
    ]
